// components/project/SettingsSection.tsx
"use client";

import React, { useCallback, useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
    Wand2,
    Settings2,
    Layout,
    Palette,
    MonitorSmartphone,
    Sparkles,
    RotateCcw,
    Info,
    Share,
    Save,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import ProjectThemes from "./ProjectThemes";
import { themeNames } from "@/constants";
import { Input } from "../ui/input";
import { Project, ScreenConfig } from "@/db/schema";
import { useRouter } from "next/navigation";
import axios from "axios";
import { useProject } from "@/context/ProjectContext";


interface SettingsSectionProps {
    project: Project;
    initialScreenConfig: ScreenConfig[] | [];
}

export default function SettingsSection({ project, initialScreenConfig }: SettingsSectionProps) {
    const router = useRouter();
    const hasAutoGenerated = useRef<boolean>(false);
    const [projectName, setProjectName] = useState(project.projectName || "");
    const [prompt, setPrompt] = useState(project.userInput || "");
    const [device, setDevice] = useState(project.deviceType || "desktop");
    const [stylePreset, setStylePreset] = useState(project.theme || "modern");
    const [quality, setQuality] = useState(75);
    const [darkMode, setDarkMode] = useState(true);
    const [autoGenerate, setAutoGenerate] = useState(false);

    const { setIsGenerating } = useProject();






    // Auto-generate when there are no existing mockups 
    const handleGenerate = useCallback(async () => {
        if (!prompt.trim()) {
            toast.error("Please enter a prompt first");
            return;
        }

        setIsGenerating(true);

        const payload = {
            prompt: prompt.trim(),
            deviceType: device,
            theme: stylePreset,
            quality,
            darkMode,
            projectName: projectName.trim(),
            projectId: project.projectId,
            id: project.id
        };

        try {
            const { data, status } = await axios.post(
                `/api/projects/${project.id}/generate`,
                payload
            );

            if (status === 201) {
                console.log({data});
                toast.success("Mockup generated! ✨");
                router.refresh();
            }
        } catch (error) {
            console.error(error);
            toast.error("Failed to generate mockup");
        } finally {
            setIsGenerating(false);
        }
    }, [
        prompt,
        device,
        stylePreset,
        quality,
        darkMode,
        projectName,
        project.id,
        router,
        project.projectId,
        setIsGenerating
    ]);
    useEffect(() => {
        if (initialScreenConfig.length === 0 && !hasAutoGenerated.current && prompt.trim().length > 15) {
            hasAutoGenerated.current = true;
            handleGenerate();
        }
    }, [handleGenerate, initialScreenConfig.length, prompt]);

    const handleReset = () => {
        setProjectName("");
        setPrompt("");
        setDevice("desktop");
        setStylePreset("modern");
        setQuality(75);
        setDarkMode(true);
        setAutoGenerate(false);
        toast.info("Settings reset to defaults");
    };

    return (
        <div
            className={cn(
                "w-full md:w-80 lg:w-96 shrink-0 border-r bg-background/80 backdrop-blur-sm",
                "sticky top-0 h-screen overflow-y-auto scrollbar-thin"
            )}
        >
            <div className="p-5 md:p-6 flex flex-col h-full">
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-2">
                        <Settings2 className="h-5 w-5 text-primary" />
                        <h2 className="text-xl font-semibold tracking-tight">Project Settings</h2>
                    </div>
                    <Badge variant="outline" className="text-xs">
                        New Project
                    </Badge>
                </div>

                <Tabs defaultValue="prompt" className="flex-1 flex flex-col">
                    <TabsList className="grid w-full grid-cols-2 mb-6">
                        <TabsTrigger value="prompt">
                            <Wand2 className="mr-2 h-4 w-4" />
                            Prompt
                        </TabsTrigger>
                        <TabsTrigger value="appearance">
                            <Palette className="mr-2 h-4 w-4" />
                            Appearance
                        </TabsTrigger>
                    </TabsList>

                    <TabsContent value="prompt" className="flex-1 mt-0 space-y-6">
                        <Card>
                            <CardHeader className="pb-3">
                                <CardTitle className="text-base">Description / Prompt</CardTitle>
                                <CardDescription>
                                    Describe your UI/UX idea or edit the initial prompt
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-4">
                                <Input
                                    placeholder="Project title..."
                                    className="w-full"
                                    value={projectName}
                                    onChange={e => setProjectName(e.target.value)}
                                />
                                <Textarea
                                    placeholder="A modern SaaS dashboard with dark mode, neumorphic cards, sidebar navigation, analytics widgets, user profile dropdown..."
                                    className="min-h-45 resize-none"
                                    value={prompt}
                                    onChange={(e) => setPrompt(e.target.value)}
                                />

                                <div className="flex items-center justify-between text-sm">
                                    <div className="flex items-center gap-1.5 text-muted-foreground">
                                        <Info className="h-3.5 w-3.5" />
                                        <span>Be specific for better results</span>
                                    </div>
                                    <span className="text-muted-foreground">
                                        {prompt.length} / 800
                                    </span>
                                </div>
                            </CardContent>
                        </Card>

                        <Card>
                            <CardHeader className="pb-3">
                                <CardTitle className="text-base">Target Device</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <Select value={device} onValueChange={setDevice}>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select target device" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="mobile">
                                            <div className="flex items-center gap-2">
                                                <MonitorSmartphone className="h-4 w-4" />
                                                Mobile App
                                            </div>
                                        </SelectItem>
                                        <SelectItem value="tablet">Tablet</SelectItem>
                                        <SelectItem value="desktop">
                                            <div className="flex items-center gap-2">
                                                <Layout className="h-4 w-4" />
                                                Website / Desktop
                                            </div>
                                        </SelectItem>
                                    </SelectContent>
                                </Select>
                            </CardContent>
                        </Card>
                    </TabsContent>

                    <TabsContent value="appearance" className="flex-1 mt-0 space-y-6">
                        <Card>
                            <CardHeader className="pb-3">
                                <CardTitle className="text-base">Design Style</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <Select value={stylePreset} onValueChange={setStylePreset}>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Select style preset" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        {themeNames.map((themeName, index) => (
                                            <SelectItem key={index} value={themeName.value}>{themeName.title}</SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </CardContent>
                        </Card>

                        <Card>
                            <CardHeader className="pb-3">
                                <CardTitle className="text-base">Quality & Detail</CardTitle>
                                <CardDescription>
                                    Higher = more detailed but slower
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-6 pt-2">
                                <div className="space-y-4">
                                    <div className="flex justify-between text-sm">
                                        <span>Quality</span>
                                        <span>{quality}%</span>
                                    </div>
                                    <Slider
                                        value={[quality]}
                                        onValueChange={([v]) => setQuality(v)}
                                        max={100}
                                        step={5}
                                    />
                                </div>

                                <div className="flex items-center justify-between">
                                    <div className="space-y-0.5">
                                        <Label htmlFor="dark-mode">Prefer Dark Mode</Label>
                                        <p className="text-xs text-muted-foreground">
                                            Most mockups will use dark theme
                                        </p>
                                    </div>
                                    <Switch
                                        id="dark-mode"
                                        checked={darkMode}
                                        onCheckedChange={setDarkMode}
                                    />
                                </div>

                                <div className="flex items-center justify-between">
                                    <div className="space-y-0.5">
                                        <Label htmlFor="auto-generate">Auto-generate on save</Label>
                                        <p className="text-xs text-muted-foreground">
                                            Start generation automatically
                                        </p>
                                    </div>
                                    <Switch
                                        id="auto-generate"
                                        checked={autoGenerate}
                                        onCheckedChange={setAutoGenerate}
                                    />
                                </div>
                            </CardContent>
                        </Card>

                        <ProjectThemes setStylePreset={setStylePreset} stylePreset={stylePreset} />
                    </TabsContent>
                </Tabs>

                <div className="pt-6 mt-auto border-t space-y-3">
                    {/* add share and screenshot */}
                    <div className="grid grid-cols-2 gap-3 mb-5">
                        <Button variant={"outline"}>
                            <Share className="mr-2 w-4 h-4" />
                            Share
                        </Button>
                        <Button variant={"secondary"}>
                            <Save className="mr-2 w-4 h-4" />
                            Save
                        </Button>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                        <Button variant="outline" onClick={handleReset}>
                            <RotateCcw className="mr-2 h-4 w-4" />
                            Reset
                        </Button>
                        <Button onClick={handleGenerate} disabled={!prompt.trim()} className="px-2">
                            <Sparkles className="h-4 w-4" />
                            Generate Mockup
                        </Button>
                    </div>

                    <Button variant="ghost" size="sm" className="w-full justify-center text-muted-foreground">
                        Save as draft
                    </Button>
                </div>
            </div>
        </div>
    );
}